In [1]:
import numpy as np

In [2]:
# arr1 = np.array([1,2,3], [4,5,6])

In [3]:
arr1 = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1

array([[1, 2],
       [3, 4]])

In [6]:
print(arr1)

[[1 2]
 [3 4]]


In [7]:
arr2 = np.array([[[
    [1,2],
    [4,5]
]]])

In [8]:
arr2

array([[[[1, 2],
         [4, 5]]]])

In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr1.shape

(2, 2)

In [11]:
arr2.shape

(1, 1, 2, 2)

In [12]:
arr1.ndim

2

In [13]:
arr2.ndim

4

In [14]:
arr2.dtype

dtype('int64')

In [15]:
arr3 = np.array([[1, 2],[3., 7]])

In [16]:
arr3.dtype

dtype('float64')

In [17]:
arr3.size

4

In [18]:
type(arr3)

numpy.ndarray

In [19]:
arr3.dtype

dtype('float64')

In [20]:
import pandas as pd

In [21]:
df = pd.DataFrame(arr3)

In [22]:
df

0    1
0  1.0  2.0
1  3.0  7.0

In [23]:
arr3

array([[1., 2.],
       [3., 7.]])

In [24]:
df2 = pd.DataFrame(np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
]))

In [25]:
df2

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [26]:
arr4 = np.array([1,2,3])

In [27]:
arr4

array([1, 2, 3])

In [28]:
ones_array = np.ones(shape=(2,3))

In [29]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
zeroes_array = np.zeros(shape=(10,2))

In [31]:
zeroes_array.shape

(10, 2)

In [32]:
zeroes_array.dtype

dtype('float64')

In [33]:
zeroes_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
a = np.arange(10,100,5)

In [35]:
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [36]:
rand_arr = np.random.randint(0,10,(5,5))

In [37]:
rand_arr

array([[2, 7, 1, 6, 8],
       [7, 5, 2, 9, 8],
       [8, 3, 6, 6, 7],
       [6, 3, 5, 4, 7],
       [2, 9, 8, 5, 0]])

In [38]:
rand_2 = np.random.rand(5,2)

In [39]:
rand_2.sum()

np.float64(5.3766297058180355)

In [40]:
rand_2

array([[0.96909872, 0.38979603],
       [0.74686242, 0.48628291],
       [0.85049593, 0.67186983],
       [0.21961563, 0.04188099],
       [0.58867786, 0.41204937]])

In [41]:
np.random.seed(42)
a = np.random.randint(1,15,10)
a.sum()

np.int64(81)

In [42]:
arr4

array([1, 2, 3])

In [43]:
arr4[0]

np.int64(1)

In [44]:
arr4[2]

np.int64(3)

In [45]:
arr5 = np.array([[1,2],[3,4]])

In [46]:
arr5[0]

array([1, 2])

In [47]:
arr5[0][1]

np.int64(2)

In [48]:
a4d = np.array([[
    [1,2,33,40,58,60,73],
    [1,2,34,49,57,61,72],
    [1,2,35,48,56,62,71],
    [1,2,36,47,55,63,70],
],
[
    [1,2,33,40,58,60,73],
    [1,2,34,49,57,61,72],
    [1,2,35,48,56,62,71],
    [1,2,36,47,55,63,70],
]])

In [49]:
a4d.ndim

3

In [50]:
a4d[0]

array([[ 1,  2, 33, 40, 58, 60, 73],
       [ 1,  2, 34, 49, 57, 61, 72],
       [ 1,  2, 35, 48, 56, 62, 71],
       [ 1,  2, 36, 47, 55, 63, 70]])

In [51]:
a4d.shape

(2, 4, 7)

In [52]:
a4d[:1,:3,:5]

array([[[ 1,  2, 33, 40, 58],
        [ 1,  2, 34, 49, 57],
        [ 1,  2, 35, 48, 56]]])

In [53]:
a1d = np.array([[1,2], [3,4]])

In [54]:
a1d.shape

(2, 2)

In [55]:
a1d[:,:]

array([[1, 2],
       [3, 4]])

In [56]:
random_a3d = np.random.randint(10, size=(3,3,4))

In [57]:
random_a3d

array([[[6, 7, 4, 3],
        [7, 7, 2, 5],
        [4, 1, 7, 5]],

       [[1, 4, 0, 9],
        [5, 8, 0, 9],
        [2, 6, 3, 8]],

       [[2, 4, 2, 6],
        [4, 8, 6, 1],
        [3, 8, 1, 9]]])

In [58]:
random_a3d.shape

(3, 3, 4)

In [59]:
random_a3d[:3,:3,:4]

array([[[6, 7, 4, 3],
        [7, 7, 2, 5],
        [4, 1, 7, 5]],

       [[1, 4, 0, 9],
        [5, 8, 0, 9],
        [2, 6, 3, 8]],

       [[2, 4, 2, 6],
        [4, 8, 6, 1],
        [3, 8, 1, 9]]])

In [60]:
df = pd.DataFrame({
    'a':[10,12,13]
})

In [61]:
df

a
0  10
1  12
2  13

In [62]:
df['a']*100

0    1000
1    1200
2    1300
Name: a, dtype: int64

In [63]:
df['a'].apply(lambda x: x*100)

0    1000
1    1200
2    1300
Name: a, dtype: int64

In [64]:
df['b'] = df['a']*100

In [65]:
df['b']

0    1000
1    1200
2    1300
Name: b, dtype: int64

In [66]:
df['c'] = df['a'].apply(lambda x: x * 100)

In [67]:
df

a     b     c
0  10  1000  1000
1  12  1200  1200
2  13  1300  1300

In [68]:
df.dtypes

a    int64
b    int64
c    int64
dtype: object

In [69]:
a = np.array([1,2])
b = np.array([2,4])
a @ b

np.int64(10)

In [70]:
a * b

array([2, 8])

In [71]:
sum(a)

np.int64(3)

In [72]:
# multiply(a)

In [73]:
c = np.array([12, 45, 1, 25, 10])

In [74]:
np.max(c)

np.int64(45)

In [75]:
np.min(c)

np.int64(1)

In [76]:
np.mean(c)

np.float64(18.6)

In [77]:
np.std(c)

np.float64(15.265647709809107)

In [78]:
a100= np.random.random(1000)

In [79]:
%timeit sum(a100)
%timeit np.sum(a100)

86.9 µs ± 24.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.67 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
a

array([1, 2])

In [81]:
np.var(a)

np.float64(0.25)

In [82]:
np.std(a)

np.float64(0.5)

In [83]:
np.sqrt(np.var(a))

np.float64(0.5)

In [84]:
a

array([1, 2])

In [85]:
b

array([2, 4])

In [86]:
np.dot(a,b)

np.int64(10)

In [87]:
a @ b

np.int64(10)

In [88]:
a * b

array([2, 8])

In [89]:
item_price = np.array([12,8,90])

In [90]:
item_price.shape

(3,)

In [91]:
df = pd.DataFrame(
    item_price.reshape(1,3),
    index = ['item_price'],
    columns=['item1', 'item2', 'item3']
)

In [92]:
df

item1  item2  item3
item_price     12      8     90

In [93]:
item_price.shape

(3,)

In [94]:
item_price.shape

(3,)

In [95]:
item_price.T.shape

(3,)

In [96]:
df.shape

(1, 3)

In [97]:
item_price = item_price.reshape(3,1)

In [98]:
np.dot(df,item_price)

array([[8308]])

In [99]:
df

item1  item2  item3
item_price     12      8     90

In [100]:
item_price

array([[12],
       [ 8],
       [90]])

In [101]:
df.dot(item_price)

0
item_price  8308

In [102]:
a

array([1, 2])

In [103]:
b

array([2, 4])

In [104]:
a>b

array([False, False])

In [105]:
a<b

array([ True,  True])

In [106]:
a==b

array([False, False])

In [107]:
a!=b

array([ True,  True])

In [108]:
a in b

False

In [109]:
b in a

False

In [110]:
a is b

False

In [111]:
b is a

False

In [112]:
a not in b

True

In [113]:
b not in a

True

In [114]:
ran_mat = np.random.randint(10,size=(3, 5))

In [115]:
ran_mat

array([[7, 9, 6, 6, 6],
       [7, 0, 3, 5, 8],
       [1, 0, 9, 1, 6]])

In [116]:
np.sort(ran_mat)

array([[6, 6, 6, 7, 9],
       [0, 3, 5, 7, 8],
       [0, 1, 1, 6, 9]])

In [117]:
np.sort(ran_mat, axis=0)

array([[1, 0, 3, 1, 6],
       [7, 0, 6, 5, 6],
       [7, 9, 9, 6, 8]])

In [118]:
np.argsort(ran_mat)

array([[3, 2, 4, 0, 1],
       [1, 2, 3, 0, 4],
       [1, 0, 3, 4, 2]])

In [121]:
np.argmin(ran_mat, axis=0)

array([2, 1, 1, 2, 0])

In [120]:
ran_mat

array([[7, 9, 6, 6, 6],
       [7, 0, 3, 5, 8],
       [1, 0, 9, 1, 6]])